### ISSUE TITLE
Error when pressing the play button for the first time

### ISSUE THREAD

**Issue by sercanov** [ldn0x7dc/react-native-media-kit#10]
I attached the error screen. Actually it plays even if it fires an error but when in release mode, the app crashes no doubt.

``` javascript
<Video
      style={{height: width / (16/9)}}
      src={this.props.movieInfo.trailerUrl}
      autoplay={false}
      preload={'none'}
      loop={false}
      controls={true}
      muted={false}
      poster={'none'}>
```

![img_2662](https://cloud.githubusercontent.com/assets/10291644/17084893/5885aeb2-51d2-11e6-8aab-a96fd8e40eef.PNG)

**Comment by ldn0x7dc** [comment]
@sercanov 
Could you post more info like your react-native version? This component works on rn 0.28+.

**Comment by cande1gut** [comment]
Hi @sercanov, you are not closing the Video tag, after poster:
      poster={'none'}/>

**Comment by xiDaiDai** [comment]
same error,RN version 0.29+

**Comment by sercanov** [comment]
@ldn0x7dc I'll re-open this issue when I tried with latest version of React Native. Thanks.

@cande1gut I'm closing it in the lines below.
