### ISSUE TITLE
Full Screen in mobile work but in tablet get a litle white space (Android)

### ISSUE THREAD

**Issue by ducchungtx** [ldn0x7dc/react-native-media-kit#25]
How to fit this problem ? I using project with react-native-oriention. I think problem come from 3 virtual button (back, home, ...) on tablet.
Thanks.

**Comment by Liroo** [comment]
I think it's your own implementation. [stackoverflow](http://stackoverflow.com/)

**Comment by ducchungtx** [comment]
@Liroo thanks. I must learn Android to do that.
