### ISSUE TITLE
iOS上报undefined is not an object(evaluatin 'UIManager.RCTMediaPlayerView.Commands'  MediaPlayerView.js:151:35

### ISSUE THREAD

**Issue by feixue1232** [ldn0x7dc/react-native-media-kit#49]
iOS上报undefined is not an object(evaluatin 'UIManager.RCTMediaPlayerView.Commands'  MediaPlayerView.js:151:35, 谁遇到过这个问题，好心人帮助，，help~~~~

**Comment by vae-xing** [comment]
我也遇到这个问题了，请问你解决了吗？

**Comment by p2mThinknet** [comment]
新版本的rn对ios有调整

**Comment by vae-xing** [comment]
@p2mThinknet 需要更新RN到最新版本吗？

**Comment by feixue1232** [comment]
@vae-xing 解决了。用rn0.42.0版本， 0.43.0会出错，可能还没适配这个版本。。

**Comment by vae-xing** [comment]
@feixue1232 我用的rn0.39.0版本的没升级rn呢,但是报错'UIManager.RCTMediaPlayerView.Commands'MediaPlayerView.js：151：35,你没遇到吗？

**Comment by feixue1232** [comment]
@vae-xing 如果你用0.39的话，那就试一下降低react-native-media-kit的版本吧。。。我现在把项目升到0.42了，最新的react-native-media-kit版本和0.42匹配，运行正常。
